# Generated by Django 3.0.8 on 2020-08-14 15:12

import HFhtml.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(default=None, verbose_name='Товар')),
                ('phone', models.TextField(default=None, verbose_name='Телефон')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('status', models.TextField(choices=[('Получен', 'Получен'), ('Просмотрен', 'Просмотрен'), ('Обработан', 'Обработан')], default='Получен', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, verbose_name='Наименование')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('sale', models.IntegerField(default=0, verbose_name='Скидка')),
                ('age', models.TextField(default='', verbose_name='Возраст')),
                ('tech', models.TextField(default=None, verbose_name='Тех.характеристики')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('reset', models.TextField(default=None, verbose_name='Ссылка восстановления')),
                ('ref', models.IntegerField(default=0, verbose_name='Referral')),
                ('vk', models.TextField(default=None, verbose_name='ВКонтакте ID')),
                ('inst', models.TextField(default=None, verbose_name='Instagram ID')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', HFhtml.models.UsersManager()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(default=None, verbose_name='Телефон')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HFhtml.Items', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/img', verbose_name='Картинка')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_img', to='HFhtml.Items', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
