# Generated by Django 3.0.8 on 2020-10-17 12:13

import HFhtml.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(default=None, verbose_name='Товар')),
                ('phone', models.TextField(default=None, verbose_name='Телефон')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('status', models.TextField(choices=[('Получен', 'Получен'), ('Просмотрен', 'Просмотрен'), ('Обработан', 'Обработан')], default='Получен', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, verbose_name='Город')),
                ('phone', models.TextField(default=None, null=True, verbose_name='Телефон')),
                ('address', models.TextField(default=None, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='CityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('sale', models.IntegerField(default=0, verbose_name='Скидка')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town', to='HFhtml.City', verbose_name='Город заказа')),
            ],
            options={
                'verbose_name': 'Товар по городам',
                'verbose_name_plural': 'Товары по городам',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, verbose_name='Наименование')),
                ('age', models.TextField(default='', verbose_name='Возраст')),
                ('tech', models.TextField(default=None, verbose_name='Тех.характеристики')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(default=None, verbose_name='Телефон')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='E-mail')),
                ('pay', models.TextField(choices=[('online', 'Онлайн'), ('offline', 'При получении')], default='Онлайн', verbose_name='Оплата')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.TextField(choices=[('В работе', 'В работе'), ('Ждем оплаты', 'Ждем оплаты'), ('Оплачен', 'Оплачен'), ('Завершен', 'Завершен')], default='В работе', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('phone', models.TextField(default=None, max_length=10, null=True, verbose_name='Телефон')),
                ('reset', models.TextField(default=None, verbose_name='Ссылка восстановления')),
                ('ref', models.IntegerField(default=0, verbose_name='Referral')),
                ('vk', models.TextField(default=None, null=True, verbose_name='ВКонтакте ID')),
                ('inst', models.TextField(default=None, null=True, verbose_name='Instagram ID')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', HFhtml.models.UsersManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='HFhtml.CityPrice', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='HFhtml.Orders', verbose_name='Номер заказа')),
            ],
            options={
                'verbose_name': 'Товар в Заказе',
                'verbose_name_plural': 'Товары в Заказе',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=HFhtml.models.content_file_name, verbose_name='Картинка')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_img', to='HFhtml.Items', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='cityprice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_items', to='HFhtml.Items', verbose_name='Товар'),
        ),
    ]
