# Generated by Django 3.0.8 on 2020-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='inst',
            field=models.TextField(default=None, null=True, verbose_name='Instagram ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='vk',
            field=models.TextField(default=None, null=True, verbose_name='ВКонтакте ID'),
        ),
    ]
