# Generated by Django 3.0.8 on 2020-08-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0002_auto_20200814_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='items/img/<django.db.models.fields.related.ForeignKey>/', verbose_name='Картинка'),
        ),
    ]
