# Generated by Django 3.0.8 on 2020-08-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0003_auto_20200814_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='items/img/None/', verbose_name='Картинка'),
        ),
    ]
