# Generated by Django 3.0.8 on 2020-08-14 15:41

import HFhtml.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0004_auto_20200814_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=HFhtml.models.content_file_name, verbose_name='Картинка'),
        ),
    ]
