# Generated by Django 3.0.8 on 2021-01-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0004_orderitem_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='inst_status',
            field=models.TextField(choices=[('subscribe', 'Подписан'), ('not subscribe', 'Не подписан')], default='Не подписан', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='users',
            name='vk_status',
            field=models.TextField(choices=[('subscribe', 'Подписан'), ('not subscribe', 'Не подписан')], default='Не подписан', verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='cityprice',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена без скидки'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_price',
            field=models.FloatField(default=0, verbose_name='Цена при заказе'),
        ),
    ]
