# Generated by Django 3.0.8 on 2020-08-16 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0005_auto_20200814_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='HFhtml.Items', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='HFhtml.Orders', verbose_name='Номер заказа')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='HFhtml.Items', verbose_name='Цена')),
            ],
        ),
    ]
