# Generated by Django 3.0.8 on 2020-08-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0006_auto_20200816_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товар в Заказе', 'verbose_name_plural': 'Товары в Заказе'},
        ),
    ]
