# Generated by Django 3.0.8 on 2020-08-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0007_auto_20200816_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
