# Generated by Django 3.0.8 on 2020-08-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0009_remove_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
    ]
