# Generated by Django 3.0.8 on 2020-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0010_remove_orders_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pay',
            field=models.TextField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн')], default='Онлайн', verbose_name='Оплата'),
        ),
    ]
