# Generated by Django 3.0.8 on 2020-08-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0011_orders_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pay',
            field=models.TextField(choices=[('online', 'Онлайн'), ('offline', 'При получении')], default='Онлайн', verbose_name='Оплата'),
        ),
    ]
