# Generated by Django 3.0.8 on 2020-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0013_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.TextField(default=None, max_length=10, null=True, verbose_name='Телефон'),
        ),
    ]
