# Generated by Django 3.0.8 on 2020-08-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0014_auto_20200822_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.TextField(choices=[('in process', 'В обработке'), ('not paid', 'Ждем оплаты'), ('paid', 'Оплачен'), ('complete', 'Завершен')], default='В обработке', verbose_name='Статус'),
        ),
    ]
