# Generated by Django 3.0.8 on 2020-08-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0015_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.TextField(choices=[('В обработке', 'В обработке'), ('Ждем оплаты', 'Ждем оплаты'), ('Оплачен', 'Оплачен'), ('Завершен', 'Завершен')], default='В обработке', verbose_name='Статус'),
        ),
    ]
