# Generated by Django 3.0.8 on 2020-08-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0016_auto_20200823_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.TextField(choices=[('В работе', 'В работе'), ('Ждем оплаты', 'Ждем оплаты'), ('Оплачен', 'Оплачен'), ('Завершен', 'Завершен')], default='В работе', verbose_name='Статус'),
        ),
    ]
