# Generated by Django 3.0.8 on 2020-08-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0018_orders_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
    ]
