# Generated by Django 3.0.8 on 2020-08-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFhtml', '0019_remove_orders_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='E-mail'),
        ),
    ]
